<h4>Numpy Array</h4>


In [2]:
import numpy as np #numpy means numerical python

#creating a 1-D array
arr1d = np.array([1,2,3,4,5])
print("1-D array:")
print(arr1d)

#creating a 2-D array
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2-D array:")
print(arr2d)

1-D array:
[1 2 3 4 5]
2-D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


<h4>Modified data type</h4>

In [30]:
a=np.array([1,2,3])
print(a)
b = np.array([(1,2,3),(4,5,6)],dtype=float)
print(b)

[1 2 3]
[[1. 2. 3.]
 [4. 5. 6.]]


<h4>Array Operation</h4>

In [19]:
np.ones((4,3,4),dtype=int)
np.arange(10,25,5)
np.linspace(0,2,9)
np.full((2,2),7)
np.eye(2)
np.random.random((2,2))

array([[0.82829401, 0.22667009],
       [0.14944604, 0.64960129]])

<h4>Array Slicing</h4>

In [22]:
arr_sum = np.sum(arr1d)
arr_mean = np.mean(arr1d)
arr_max = np.max(arr1d)
arr_min = np.min(arr1d)

print("Array Operations:")
print("Sum of array1d:",arr_sum)
print("Mean of array1d:",arr_mean)
print("Max of array1d:",arr_max)
print("Min of array1d:",arr_min)

Array Operations:
Sum of array1d: 15
Mean of array1d: 3.0
Max of array1d: 5
Min of array1d: 1


<h4>Subtraction</h4>

In [36]:
c = np.ones([1,3],dtype=int)

b = b.astype(int)#convert b to int

g = c-b
print(g)

ab= a-b
print(ab)
print("\n")
print(np.subtract(a,b))
print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 0 -1 -2]
 [-3 -4 -5]]
[[ 0  0  0]
 [-3 -3 -3]]


[[ 0  0  0]
 [-3 -3 -3]]
[[2 4 6]
 [5 7 9]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]


<h4>Array Slicing</h4>

In [40]:
print("Indexing and Slicing:")
print("1-D array:")
print(arr1d)

print("Array at index 0:",arr1d[1])
print("Array at index 2:",arr1d[2])
print("Slice from 1st to 4th index:",arr1d[1:4])

Indexing and Slicing:
1-D array:
[3 2 3 4 5]
Array at index 0: 2
Array at index 2: 3
Slice from 1st to 4th index: [2 3 4]


<h4>Exercises</h4>

In [54]:
arr = np.random.randint(1,10,(3,3))
print("3x3 array:")
print(arr)

print("Sum of all elements:",np.sum(arr))

3x3 array:
[[2 3 7]
 [6 8 5]
 [2 1 4]]
Sum of all elements: 38


In [43]:
arr1 = np.array([12,52,33])
arr2 = np.array([43,52,66])

arr3 = arr1*arr2
print("Array 1:",arr1)
print("Array 2:",arr2)
print("Array 3:",arr3)

Array 1: [12 52 33]
Array 2: [43 52 66]
Array 3: [ 516 2704 2178]


<h3>Pandas</h3>

In [57]:
import pandas as pd

#creating a dataframe from a dictionary
data = {'Name':['Alice','Bob','Charlie','David','Eva'],
        'Age':[25,30,22,28,24],
        'Salary':[50000,60000,45000,70000,55000]
        }

df = pd.DataFrame(data)
print("DataFrame")
print(df)

DataFrame
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   22   45000
3    David   28   70000
4      Eva   24   55000


<h4>Selecting data from datafram</h4>

In [64]:
print("Age 30 only:")
print(df[df['Age']==30])
print("\nDf sliced:\n",df[1:2])

print(df[df['Salary']==50000])

Age 30 only:
  Name  Age  Salary
1  Bob   30   60000

Df sliced:
   Name  Age  Salary
1  Bob   30   60000
    Name  Age  Salary
0  Alice   25   50000


<h4>Selecting data from position (iloc)</h4>

In [72]:
#selecting the first row
row_0 = df.iloc[0]
print("\nSelecting by position:(iloc)")
print("First row:\n")
print(row_0)

#selecting the value in the second row and 'Age' column
value_2nd_row_age_col = df.iloc[1,df.columns.get_loc('Age')]
print("\nValue in 2nd row and 'Age' column:",value_2nd_row_age_col)


Selecting by position:(iloc)
First row:

Name      Alice
Age          25
Salary    50000
Name: 0, dtype: object

Value in 2nd row and 'Age' column: 30


#### Selecting data from label (loc)

In [75]:
selected_rows = df.iloc[[1,3]]
print("\nSelceting by labels:(loc)")
print("Selected rows:\n")
print(selected_rows)

#Selecting y a specific cell by label
cell_Label = df.loc[2,'Salary']
print("\nCell at row 2 and column 'Salary':",cell_Label)


Selceting by labels:(loc)
Selected rows:

    Name  Age  Salary
1    Bob   30   60000
3  David   28   70000

Cell at row 2 and column 'Salary': 45000


#### Bollean indexing

In [87]:
#boolean indexing
print("\nBoolean indexing:")
high_salary = df[df['Salary']>55000]

print("Employees with salary > 55000:\n")
print(high_salary)


Boolean indexing:
Employees with salary > 55000:

    Name  Age  Salary  Experience
1    Bob   30   60000           5
3  David   28   70000           7
5   Arik   33   80000           8


#### setting a new value to a dataframe

In [94]:
#Setting a new value in the DataFrame
df.loc[0,'Age']=26
print("\nSetting Values in DataFrame:")
print("\nNew value in DataFrame:")
print(df)

# #Setting a new value with default values
# df['Experience'] = [2,5,1,7,3] #add a new column
# print("\nNew column 'Experience':")
# print(df)

# #adding new rows
# df.loc[5] = ['Arik',33,80000,8]
# print("\nNew row:")
# print(df)


Setting Values in DataFrame:

New value in DataFrame:
      Name  Age  Salary  Experience
0    Alice   26   50000           2
1      Bob   30   60000           5
2  Charlie   22   45000           1
3    David   28   70000           7
4      Eva   24   55000           3
5     Arik   33   80000           8


#### Exercises

In [101]:
#select the last two rows of the dataframe
size = df.shape[0]
last_two_rows = df.iloc[size-2:]
print("\nLast two rows:")
print(last_two_rows)

#create new df with employees under 30 and salary > 50000
new_df = df[(df['Age']<30) & (df['Salary']>50000)]
print("\nNew DataFrame:")
print(new_df)

#set the salaray of 'Charlie' to 48000 in df
df.loc[df['Name']=='Charlie','Salary']=48000
print("\nNew DataFrame with edited salary:")
print(df)


Last two rows:
   Name  Age  Salary  Experience
4   Eva   24   55000           3
5  Arik   33   80000           8

New DataFrame:
    Name  Age  Salary  Experience
3  David   28   70000           7
4    Eva   24   55000           3

New DataFrame with edited salary:
      Name  Age  Salary  Experience
0    Alice   26   50000           2
1      Bob   30   60000           5
2  Charlie   22   48000           1
3    David   28   70000           7
4      Eva   24   55000           3
5     Arik   33   80000           8


#### Discussion
In this lab we learned about many built in libraries of python and how to use them. We learned about numpy and pandas and how to use them to manipulate data. We also learned about the different types of data structures in python and how to use them. We learned about lists, tuples, dictionaries, and sets. We also learned about the different types of data types in python and how to use them. We learned about strings, integers, floats, and booleans. We also learned about the different types of operators in python and how to use them. We learned about arithmetic operators, comparison operators, logical operators, and assignment operators. We also learned about the different types of control flow statements in python and how to use them. We learned about if statements, for loops, while loops, and try except statements. We also learned about the different types of functions in python and how to use them. We learned about built in functions, user defined functions, and lambda functions. We also learned about the different types of errors in python and how to use them. We learned about syntax errors, runtime errors, and logical errors. We also learned about the different types of modules in python and how to use them. We learned about built in modules, user defined modules, and third party modules. We also learned about the different types of classes in python and how to use them. We learned about class attributes, class methods, and class constructors. We also learned about the different types of exceptions in python and how to use them. We learned about built in exceptions, user defined exceptions, and exception handling. We also learned about the different types of file operations in python and how to use them. We learned about reading files, writing files, and appending files. We also learned about the different types of data structures in numpy and how to use them. We learned about numpy arrays, modified data types, array operations, array slicing, and subtraction. We also learned about the different types of data structures in pandas and how to use them. We learned about selecting data from a dataframe, selecting data from position, selecting data from label, boolean indexing, and setting a new value to a dataframe.